# Generated by Django 4.2.2 on 2023-07-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercado',
            name='bairro',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mercado',
            name='rua',
            field=models.CharField(max_length=100),
        ),
    ]
