# Generated by Django 4.2.2 on 2023-07-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_mercado_bairro_alter_mercado_rua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=60),
        ),
    ]
