# Generated by Django 4.2.2 on 2023-07-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessão',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='sessao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.sessão'),
            preserve_default=False,
        ),
    ]
