# Generated by Django 4.2.2 on 2023-08-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercado',
            name='imagem',
            field=models.ImageField(default=None, upload_to='imagens_mercados/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=None, upload_to='imagens_produtos/'),
            preserve_default=False,
        ),
    ]
